require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comments"
require "user.gitsigns"
require "user.nvimtree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.dashboard"

-- LPS
require "user.lsp.lang.pyright"
require "user.lsp.lang.clang"
-- require "user.lsp.lang.sumneko_lua"
require "user.lsp.lang.bashls"
