format = "$character"
right_format = "$all$username$hostname"

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[username]
format = "[$user]($style)@"
style_user = "bold green"
style_root = "bold red"
show_always = true

[hostname]
format = "[$hostname]($style)"
style = "bold dimmed blue"
ssh_only = false

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[  ](bold green)"
error_symbol = "[  ](bold red) "
vimcmd_symbol = "[  ](bold green)"

[line_break]
disabled = true

[directory]
truncation_length = 2
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[lua]
symbol = " "

[java]
symbol = " "
format = "[$symbol]($style)"
style = "bold dimmed red"

[rust]
symbol = " "
