# ────────────── Autostart ──────────────
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = awww-daemon
exec-once = awww img $HOME/Nextcloud/Wallpapers/aishot-2377.jpg
exec-once = bash $HOME/.config/screenlayout/main.sh
exec-once = gnome-keyring-daemon --start
exec-once = keepassxc
exec-once = nextcloud
exec-once = nm-applet
exec-once = shelly-notifications
exec-once = waybar
