# ────────────── Window rules ──────────────

# Floating windows
windowrule = isfloating:1,width:1920,height:1080,appid:org.cachyos.hello
windowrule = isfloating:1,width:1920,height:1080,appid:org.keepassxc.KeePassXC
windowrule = isfloating:1,width:1920,height:1080,appid:org.pulseaudio.pavucontrol
windowrule = isfloating:1,width:640,height:480,appid:gnucash,title:GnuCash Tip Of The Day
windowrule = isfloating:1,width:640,height:480,appid:org.keepassxc.KeePassXC,title:KeePassXC - Passkey credentials
windowrule = isfloating:1,width:640,height:480,appid:org.mozilla.Thunderbird,title:Reminder
windowrule = isfloating:1,width:640,height:480,appid:qalculate-gtk
windowrule = isfloating:1,width:640,height:480,no_force_center:1,appid:com.nextcloud.desktopclient.nextcloud
windowrule = isfloating:1,width:640,height:480,title:Picture-in-Picture

# Send RS to tag #4
windowrule = tags:4,appid:RuneScape
windowrule = tags:4,appid:BoltLauncher

# Blur on windows
windowrule = focused_opacity:0.9,unfocused_opacity:0.7,appid:com.mitchellh.ghostty

# ────────────── Layer rules ──────────────
layerrule = animation_type_open:zoom,layer_name:wofi
layerrule = animation_type_close:zoom,layer_name:wofi
