-- require("rangeler.treesitter")
require("rangeler.autopairs")
require("rangeler.cmp")
require("rangeler.colorscheme")
require("rangeler.comments")
require("rangeler.gitsigns")
require("rangeler.keymaps")
require("rangeler.lsp._mason")
require("rangeler.lsp.handlers")
require("rangeler.evil_lualine")
require("rangeler.nvimtree")
require("rangeler.options")
require("rangeler.plugins")
require("rangeler.telescope")
require("rangeler.tablemode")