################
### MONITORS ###
################

source = ~/.config/hypr/conf/monitors.conf


###################
### KEYBINDINGS ###
###################

source = ~/.config/hypr/conf/keybinds.conf


#################
### AUTOSTART ###
#################

source = ~/.config/hypr/conf/autostart.conf


#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24


#####################
### LOOK AND FEEL ###
#####################

source = ~/.config/hypr/look/animations.conf
source = ~/.config/hypr/look/decoration.conf
source = ~/.config/hypr/look/general.conf
source = ~/.config/hypr/look/layout.conf
source = ~/.config/hypr/look/misc.conf


#############
### INPUT ###
#############

source = ~/.config/hypr/conf/input.conf


##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
