#################
### AUTOSTART ###
#################

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = dunst --config ~/.config/dunst/dunstrc
exec-once = hyprpaper
exec-once = kdeconnect-indicator
exec-once = keepassxc
exec-once = nextcloud
exec-once = nm-applet
exec-once = waybar
