return {
    -- Useful plugin to show you pending keybinds.
    'folke/which-key.nvim',
    event = 'VimEnter', -- Sets the loading event to 'VimEnter'
    opts = {
        preset = 'helix',
        delay = 250,
        win = {
            title = 'Keybinds',
            title_pos = 'center',
        },
        icons = {
            mappings = vim.g.have_nerd_font,
            keys = vim.g.have_nerd_font and {} or {
                Up = '<Up> ',
                Down = '<Down> ',
                Left = '<Left> ',
                Right = '<Right> ',
                C = '<C-…> ',
                M = '<M-…> ',
                D = '<D-…> ',
                S = '<S-…> ',
                CR = '<CR> ',
                Esc = '<Esc> ',
                ScrollWheelDown = '<ScrollWheelDown> ',
                ScrollWheelUp = '<ScrollWheelUp> ',
                NL = '<NL> ',
                BS = '<BS> ',
                Space = '<Space> ',
                Tab = '<Tab> ',
                F1 = '<F1>',
                F2 = '<F2>',
                F3 = '<F3>',
                F4 = '<F4>',
                F5 = '<F5>',
                F6 = '<F6>',
                F7 = '<F7>',
                F8 = '<F8>',
                F9 = '<F9>',
                F10 = '<F10>',
                F11 = '<F11>',
                F12 = '<F12>',
            },
        },

        -- Document existing key chains
        spec = {
            { '<leader>O', group = '[O]bsidian' },
            { '<leader>S', group = '[S]ymbols' },
            { '<leader>a', group = '[A]vante' },
            { '<leader>b', group = '[B]uffer', mode = { 'n', 'x' } },
            { '<leader>c', group = '[C]ode', mode = { 'n', 'x' } },
            { '<leader>f', group = '[F]ind' },
            { '<leader>g', group = '[G]o To', mode = { 'n', 'v' } },
            { '<leader>h', group = 'Git [H]unk', mode = { 'n', 'v' } },
            { '<leader>l', group = '[L]aTeX' },
            { '<leader>o', group = '[O]pen' },
            { '<leader>r', group = '[R]ename' },
            { '<leader>s', group = '[S]earch' },
            { '<leader>t', group = '[T]oggle' },
            { 'gr', group = 'LSP Actions' },
        },
    },
}
