require "launch" -- require spec function

-- Plugins here
spec "plugins.autopairs"
spec "plugins.bufferline"
spec "plugins.cmp"
spec "plugins.colorscheme"
spec "plugins.comment"
spec "plugins.copilot"
spec "plugins.dap"
spec "plugins.dapui"
spec "plugins.dashboard"
spec "plugins.diffview"
spec "plugins.gitsigns"
spec "plugins.harpoon"
spec "plugins.icons"
spec "plugins.indentline"
spec "plugins.leap"
spec "plugins.lspconfig"
spec "plugins.lspsaga"
spec "plugins.lualine"
spec "plugins.mason"
spec "plugins.null-ls"
spec "plugins.nvimtree"
spec "plugins.telescope"
spec "plugins.toggleterm"
spec "plugins.treesitter"
spec "plugins.trouble"
spec "plugins.whichkey"

require "plugins.lazy"
